window.HCTK_VARIANT_CONFIG = {
  "variant": "intervention",
  "dbName": "hctk-serverless-pwa",
  "dbVersion": 3,
  "scheduleIdPrefix": "hctk",
  "uidDomain": "hctk-serverless-pwa",
  "prodId": "-//HCTK//Intervention PWA//EN",
  "themeColor": "#b8282d",
  "labels": {
    "cardsTabLabel": "Cards",
    "itemNoun": "card",
    "itemPlural": "cards",
    "todayTitle": "Learning Card",
    "nextDueLoading": "Next card: loading...",
    "defaultPrompt": "Placeholder question",
    "noDueHeading": "No learning card due today",
    "noDueBody": "",
    "blockedHeading": "No learning card due from this link",
    "blockedBody": "This calendar link is outside its scheduled participant due window. Cards are available only during their scheduled due window.",
    "calendarInvalidBody": "Regenerate the matching calendar or open a valid activity link.",
    "contentFallback": "Learning card",
    "contentTypeFallback": "Placeholder content type",
    "contentViewedDetail": "Participant viewed the current learning card.",
    "contentCompletedDetail": "Participant marked the scheduled refresher complete.",
    "adminPreviewDetail": "Admin opened a scheduled learning card preview.",
    "calendarName": "HCTK Refresher Reminders",
    "icsFilename": "hctk-six-month-reminders.ics",
    "testIcsFilename": "hctk-test-reminders.ics"
  }
};

window.HCTK_CONTENT_BANK_VERSION = 'spreadsheet-16c604bd016c';

window.HCTK_CONTENT_BANK = [
  {
    id: 'content-001',
    activityId: '1/26',
    sequence: 1,
    format: 'Fact',
    title: 'Severe bleeding can become life-threatening before professional help arrives.',
    prompt: 'When bleeding is heavy, act immediately: make sure the scene can be approached safely, get emergency help moving, find the bleeding source, and start bleeding control.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '1, 2',
    citationReferences: 'Hewett Brumberg EK, Douma MJ, Alibertis K, et al. 2024 American Heart Association and American Red Cross guidelines for first aid. Circulation. 2024;150(24):e519-e579. doi:10.1161/CIR.0000000000001281\nAmerican Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external'
  },
  {
    id: 'content-002',
    activityId: '2/26',
    sequence: 2,
    format: 'Question',
    title: 'Which finding most strongly suggests life-threatening bleeding?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'A small scrape with slow bleeding',
      'Bleeding that stopped after one tissue',
      'Blood spurting, pooling, or soaking clothing',
      'A bruise with no active bleeding'
    ],
    correctIndex: 2,
    rationale: 'A: A small scrape is usually not life-threatening bleeding.\nB: Bleeding that stops quickly is less concerning than uncontrolled bleeding.\nC: Spurting, pooling, or soaked clothing suggests major ongoing blood loss.\nD: A bruise without active bleeding does not match the severe external bleeding scenario.',
    citationNumbers: '2, 4',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nMayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-003',
    activityId: '3/26',
    sequence: 3,
    format: 'Fact',
    title: 'Check that the scene is safe before giving care.',
    prompt: 'Before approaching, look for hazards such as traffic, weapons, fire, electricity, sharp objects, unstable structures, or other threats. If the scene is unsafe, call for help and do not enter.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '2, 4',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nMayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-004',
    activityId: '4/26',
    sequence: 4,
    format: 'Question',
    title: 'What should you check before giving care for heavy bleeding?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'That the scene is safe enough to approach',
      'Pack the wound immediately',
      'Remove any tourniquet that is already in place',
      'Wait to see if the bleeding stops on its own'
    ],
    correctIndex: 0,
    rationale: 'A: Check scene safety before hands-on care.\nB: Packing may be needed later, but safety comes first.\nC: A tourniquet should not be removed by a lay responder once applied.\nD: Heavy bleeding requires action once the scene is safe.',
    citationNumbers: '2, 4',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nMayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-005',
    activityId: '5/26',
    sequence: 5,
    format: 'Fact',
    title: 'Emergency help should be activated as early as possible.',
    prompt: 'Call 911/EMS right away. If other people are present, assign one specific person to call so the task is not lost in the crowd.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '2, 4',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nMayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-006',
    activityId: '6/26',
    sequence: 6,
    format: 'Question',
    title: 'In a group of bystanders, which statement is the clearest way to activate emergency help?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Someone should probably call',
      'Maybe EMS will come soon',
      'You in the blue shirt, call 911 now and come back to tell me',
      'I will call after I finish everything else'
    ],
    correctIndex: 2,
    rationale: 'A: This is vague and may lead to no one calling.\nB: Waiting or assuming help is coming can delay care.\nC: It gives a specific person a clear task.\nD: Calling should happen early, not only after other steps are finished.',
    citationNumbers: '2, 4',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nMayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-007',
    activityId: '7/26',
    sequence: 7,
    format: 'Fact',
    title: 'Bleeding control works best when treatment is aimed at the actual source.',
    prompt: 'Clothing or objects can hide the wound. Expose enough of the area to see where blood is coming from and place pressure or equipment directly where it is needed.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '4',
    citationReferences: 'Mayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-008',
    activityId: '8/26',
    sequence: 8,
    format: 'Question',
    title: 'Why should enough of the wound area be uncovered during care?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'To make the injury look more dramatic',
      'To make sure treatment is applied directly to the bleeding source',
      'To clean the wound thoroughly before doing anything else',
      'To decide whether the person is embarrassed'
    ],
    correctIndex: 1,
    rationale: 'A: The purpose is not appearance.\nB: Exposure helps the responder treat the true bleeding site.\nC: Do not delay bleeding control by trying to fully clean the wound.\nD: Privacy matters, but bleeding control and correct placement are the key goals.',
    citationNumbers: '4',
    citationReferences: 'Mayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-009',
    activityId: '9/26',
    sequence: 9,
    format: 'Fact',
    title: 'Direct pressure means pressure on the bleeding source.',
    prompt: 'Use your hands, gauze, or a clean cloth to press firmly over the bleeding site. Pressure beside the wound may not compress the bleeding vessel.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '2, 4',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nMayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-010',
    activityId: '10/26',
    sequence: 10,
    format: 'Question',
    title: 'Where should direct pressure be applied?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Several inches away from the wound',
      'Directly over the bleeding source',
      'Only above the nearest joint',
      'Only after a tourniquet is placed'
    ],
    correctIndex: 1,
    rationale: 'A: Pressure away from the source may not control the bleeding.\nB: Pressure needs to compress the bleeding site.\nC: Joints are not the target for direct pressure.\nD: Direct pressure can be the first active bleeding-control step and can continue while preparing other care.',
    citationNumbers: '2, 4',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nMayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-011',
    activityId: '11/26',
    sequence: 11,
    format: 'Fact',
    title: 'Keep pressure steady on the bleeding site.',
    prompt: 'After firm pressure is applied, keep it in place while preparing the next step or waiting for help. If material becomes soaked, add more on top instead of removing the original layer.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '2, 4',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nMayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-012',
    activityId: '12/26',
    sequence: 12,
    format: 'Question',
    title: 'While preparing packing material, what should happen to pressure on the wound?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'It should be maintained if possible',
      'It should be removed so the wound can air out',
      'It should be stopped because packing replaces pressure',
      'It should be applied only to the person’s clothing'
    ],
    correctIndex: 0,
    rationale: 'A: Maintaining pressure reduces ongoing blood loss during transition.\nB: Airing out the wound does not control bleeding.\nC: Packing does not remove the need for pressure.\nD: Pressure should target the bleeding source, not just clothing.',
    citationNumbers: '2, 4',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nMayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-013',
    activityId: '13/26',
    sequence: 13,
    format: 'Fact',
    title: 'Wound packing is for wounds with a space that can be filled with material.',
    prompt: 'For a deep, compressible bleeding wound, place gauze or clean cloth into the wound space at the bleeding source, then hold firm pressure over the packed wound.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '1, 2',
    citationReferences: 'Hewett Brumberg EK, Douma MJ, Alibertis K, et al. 2024 American Heart Association and American Red Cross guidelines for first aid. Circulation. 2024;150(24):e519-e579. doi:10.1161/CIR.0000000000001281\nAmerican Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external'
  },
  {
    id: 'content-014',
    activityId: '14/26',
    sequence: 14,
    format: 'Question',
    title: 'Which action best describes wound packing?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Laying gauze loosely on top of the skin',
      'Putting material into the wound space and then holding pressure',
      'Putting a tourniquet over the chest',
      'Removing all material every few seconds to inspect the wound'
    ],
    correctIndex: 1,
    rationale: 'A: Loose surface coverage may not create pressure at the bleeding source.\nB: Packing fills the wound space and pressure helps control bleeding.\nC: Tourniquets are for limbs, not the chest.\nD: Repeated removal interrupts pressure and can worsen bleeding control.',
    citationNumbers: '1, 2',
    citationReferences: 'Hewett Brumberg EK, Douma MJ, Alibertis K, et al. 2024 American Heart Association and American Red Cross guidelines for first aid. Circulation. 2024;150(24):e519-e579. doi:10.1161/CIR.0000000000001281\nAmerican Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external'
  },
  {
    id: 'content-015',
    activityId: '15/26',
    sequence: 15,
    format: 'Fact',
    title: 'After packing a wound, keep firm pressure on it.',
    prompt: 'Packing helps only if pressure is maintained over the packed wound. Do not remove the packing. Keep pressure in place until medical responders take over.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '2, 4',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nMayo Clinic Staff. Severe bleeding: first aid. Mayo Clinic. Published October 16, 2024. Accessed May 26, 2026. https://www.mayoclinic.org/first-aid/first-aid-severe-bleeding/basics/art-20056661'
  },
  {
    id: 'content-016',
    activityId: '16/26',
    sequence: 16,
    format: 'Question',
    title: 'What does it mean if blood is still visible through packed material?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'The bleeding is controlled and no more action is needed',
      'The packing should be removed',
      'The bleeding is not controlled and more action is needed',
      'The responder should stop care and wait'
    ],
    correctIndex: 2,
    rationale: 'A: Blood still coming through the packing suggests bleeding is not controlled.\nB: Removing packing can disrupt pressure and worsen bleeding.\nC: Ongoing bleeding means more bleeding-control action is needed.\nD: Stopping care can allow continued blood loss.',
    citationNumbers: '1, 2',
    citationReferences: 'Hewett Brumberg EK, Douma MJ, Alibertis K, et al. 2024 American Heart Association and American Red Cross guidelines for first aid. Circulation. 2024;150(24):e519-e579. doi:10.1161/CIR.0000000000001281\nAmerican Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external'
  },
  {
    id: 'content-017',
    activityId: '17/26',
    sequence: 17,
    format: 'Fact',
    title: 'A tourniquet is used for severe bleeding from an arm or leg.',
    prompt: 'Use a tourniquet for life-threatening limb bleeding when direct pressure is not enough or the situation requires rapid limb bleeding control. Do not place a tourniquet on the chest, abdomen, neck, scalp, or groin.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '1, 3',
    citationReferences: 'Hewett Brumberg EK, Douma MJ, Alibertis K, et al. 2024 American Heart Association and American Red Cross guidelines for first aid. Circulation. 2024;150(24):e519-e579. doi:10.1161/CIR.0000000000001281\nAmerican Red Cross. How to apply a tourniquet. American Red Cross. Published November 27, 2024. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/articles/how-to-apply-a-tourniquet'
  },
  {
    id: 'content-018',
    activityId: '18/26',
    sequence: 18,
    format: 'Question',
    title: 'Which injury is most appropriate for a tourniquet?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Severe bleeding from the lower leg',
      'Bleeding from the abdomen',
      'Bleeding from the neck',
      'A shallow scrape on the hand'
    ],
    correctIndex: 0,
    rationale: 'A: Tourniquets are designed for severe arm or leg bleeding.\nB: A tourniquet cannot be properly applied to the abdomen.\nC: A tourniquet cannot be properly applied to the neck.\nD: A shallow scrape usually does not require a tourniquet.',
    citationNumbers: '1, 3',
    citationReferences: 'Hewett Brumberg EK, Douma MJ, Alibertis K, et al. 2024 American Heart Association and American Red Cross guidelines for first aid. Circulation. 2024;150(24):e519-e579. doi:10.1161/CIR.0000000000001281\nAmerican Red Cross. How to apply a tourniquet. American Red Cross. Published November 27, 2024. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/articles/how-to-apply-a-tourniquet'
  },
  {
    id: 'content-019',
    activityId: '19/26',
    sequence: 19,
    format: 'Fact',
    title: 'Place the tourniquet above the bleeding wound on the injured limb.',
    prompt: 'Put the tourniquet between the wound and the torso. Do not place it over a joint.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '3',
    citationReferences: 'American Red Cross. How to apply a tourniquet. American Red Cross. Published November 27, 2024. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/articles/how-to-apply-a-tourniquet'
  },
  {
    id: 'content-020',
    activityId: '20/26',
    sequence: 20,
    format: 'Question',
    title: 'For severe bleeding from the forearm, where should the tourniquet go?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Below the wound, closer to the hand',
      'Directly over the elbow joint',
      'Above the wound, closer to the torso, not over a joint',
      'Around the neck because it is fastest'
    ],
    correctIndex: 2,
    rationale: 'A: Below the wound may not stop blood flow to the injury.\nB: A joint can prevent effective compression.\nC: It should be proximal to the wound and away from joints.\nD: A neck tourniquet is never appropriate.',
    citationNumbers: '3',
    citationReferences: 'American Red Cross. How to apply a tourniquet. American Red Cross. Published November 27, 2024. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/articles/how-to-apply-a-tourniquet'
  },
  {
    id: 'content-021',
    activityId: '21/26',
    sequence: 21,
    format: 'Fact',
    title: 'Remove slack before tightening the tourniquet.',
    prompt: 'Pull the strap snug around the limb before the final tightening step. A loose strap may not stop severe bleeding.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '3',
    citationReferences: 'American Red Cross. How to apply a tourniquet. American Red Cross. Published November 27, 2024. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/articles/how-to-apply-a-tourniquet'
  },
  {
    id: 'content-022',
    activityId: '22/26',
    sequence: 22,
    format: 'Question',
    title: 'If the tourniquet strap is visibly loose before final tightening, what should be done?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Leave it loose because pain means it is harmful',
      'Remove slack and secure the strap before tightening',
      'Place it over the nearest joint',
      'Stop the scenario because direct pressure has already been tried'
    ],
    correctIndex: 1,
    rationale: 'A: A loose tourniquet may not control bleeding.\nB: Removing slack improves the chance that final tightening will be effective.\nC: A joint is not an appropriate placement site.\nD: Persistent severe bleeding still requires continued action.',
    citationNumbers: '3',
    citationReferences: 'American Red Cross. How to apply a tourniquet. American Red Cross. Published November 27, 2024. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/articles/how-to-apply-a-tourniquet'
  },
  {
    id: 'content-023',
    activityId: '23/26',
    sequence: 23,
    format: 'Fact',
    title: 'Tighten the tourniquet until the bleeding stops.',
    prompt: 'A properly tightened tourniquet can be painful. Do not loosen it because of pain; loosening can allow severe bleeding to continue.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '1, 3',
    citationReferences: 'Hewett Brumberg EK, Douma MJ, Alibertis K, et al. 2024 American Heart Association and American Red Cross guidelines for first aid. Circulation. 2024;150(24):e519-e579. doi:10.1161/CIR.0000000000001281\nAmerican Red Cross. How to apply a tourniquet. American Red Cross. Published November 27, 2024. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/articles/how-to-apply-a-tourniquet'
  },
  {
    id: 'content-024',
    activityId: '24/26',
    sequence: 24,
    format: 'Question',
    title: 'A person says the tourniquet hurts after it is applied for severe limb bleeding. What should the responder do?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Loosen it to make the person more comfortable',
      'Remove it and restart direct pressure only',
      'Keep it in place, reassure the person, and wait for trained responders',
      'Move it below the wound'
    ],
    correctIndex: 2,
    rationale: 'A: Loosening can allow bleeding to restart.\nB: Removing a tourniquet after application is not a lay-responder task.\nC: Keep it in place and reassure them while help is coming.\nD: Moving it below the wound may make it ineffective.',
    citationNumbers: '1, 3',
    citationReferences: 'Hewett Brumberg EK, Douma MJ, Alibertis K, et al. 2024 American Heart Association and American Red Cross guidelines for first aid. Circulation. 2024;150(24):e519-e579. doi:10.1161/CIR.0000000000001281\nAmerican Red Cross. How to apply a tourniquet. American Red Cross. Published November 27, 2024. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/articles/how-to-apply-a-tourniquet'
  },
  {
    id: 'content-025',
    activityId: '25/26',
    sequence: 25,
    format: 'Fact',
    title: 'Tell EMS when the tourniquet was applied and what care was given.',
    prompt: 'Record or remember the application time. When EMS arrives, report the time, where the tourniquet was placed, and any pressure or packing already used.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '2, 3',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nAmerican Red Cross. How to apply a tourniquet. American Red Cross. Published November 27, 2024. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/articles/how-to-apply-a-tourniquet'
  },
  {
    id: 'content-026',
    activityId: '26/26',
    sequence: 26,
    format: 'Question',
    title: 'Which handoff detail is most important after applying a tourniquet?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'The tourniquet application time and what bleeding-control steps were used',
      'The responder’s favorite first-aid brand',
      'Whether the person liked the color of the device',
      'A guess about how much the hospital will cost'
    ],
    correctIndex: 0,
    rationale: 'A: Time and care already provided help EMS continue treatment safely.\nB: Brand preference is not the key handoff detail.\nC: Device color does not guide medical care.\nD: Cost guesses do not help manage the bleeding emergency.',
    citationNumbers: '2, 3',
    citationReferences: 'American Red Cross. Bleeding, life-threatening external. American Red Cross. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external\nAmerican Red Cross. How to apply a tourniquet. American Red Cross. Published November 27, 2024. Accessed May 26, 2026. https://www.redcross.org/take-a-class/resources/articles/how-to-apply-a-tourniquet'
  }
];
