window.HCTK_VARIANT_CONFIG = {
  "variant": "control",
  "dbName": "hctk-control-pwa",
  "dbVersion": 1,
  "scheduleIdPrefix": "hctk-control",
  "uidDomain": "hctk-control-pwa",
  "prodId": "-//HCTK//Control PWA//EN",
  "themeColor": "#2f7d73",
  "labels": {
    "cardsTabLabel": "Activities",
    "itemNoun": "activity",
    "itemPlural": "activities",
    "todayTitle": "Study Activity",
    "nextDueLoading": "Next activity: loading...",
    "defaultPrompt": "Placeholder question",
    "noDueHeading": "No study activity due today",
    "noDueBody": "",
    "blockedHeading": "No study activity due from this link",
    "blockedBody": "This calendar link is outside its scheduled participant due window. Activities are available only during their scheduled due window.",
    "calendarInvalidBody": "Regenerate the matching calendar or open a valid activity link.",
    "contentFallback": "Study activity",
    "focusFallback": "Placeholder focus",
    "contentTypeFallback": "Placeholder content type",
    "contentViewedDetail": "Participant viewed the current study activity.",
    "contentCompletedDetail": "Participant marked the scheduled study activity complete.",
    "adminPreviewDetail": "Admin opened a scheduled study activity preview.",
    "calendarDescriptionFocusFallback": "Study activity",
    "calendarName": "HCTK Study Activity Reminders",
    "icsFilename": "hctk-control-six-month-reminders.ics",
    "testIcsFilename": "hctk-control-test-reminders.ics"
  }
};

window.HCTK_CONTENT_BANK_VERSION = 'spreadsheet-5074d7402b83';

window.HCTK_CONTENT_BANK = [
  {
    id: 'control-content-001',
    activityId: '1/26',
    sequence: 1,
    format: 'Fact',
    focus: 'Calendar basics',
    title: 'A week has seven days.',
    prompt: 'Many calendars organize time into seven-day weeks, with each day appearing in the same repeating order.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-002',
    activityId: '2/26',
    sequence: 2,
    format: 'Question',
    focus: 'Everyday objects',
    title: 'Which item is commonly used to write on a whiteboard?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Spoon',
      'Marker',
      'Pillow',
      'Key'
    ],
    correctIndex: 1,
    rationale: 'A: A spoon is used for eating or serving food.\nB: A marker is commonly used to write on a whiteboard.\nC: A pillow is used for rest or support.\nD: A key is used to open a lock.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-003',
    activityId: '3/26',
    sequence: 3,
    format: 'Fact',
    focus: 'Shapes',
    title: 'A triangle has three sides.',
    prompt: 'Triangles can look different from one another, but each triangle is defined by having three sides and three angles.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-004',
    activityId: '4/26',
    sequence: 4,
    format: 'Question',
    focus: 'Shapes',
    title: 'How many corners does a rectangle have?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Two',
      'Three',
      'Four',
      'Five'
    ],
    correctIndex: 2,
    rationale: 'A: Two corners would not make a rectangle.\nB: Three corners describes a triangle.\nC: A rectangle has four corners.\nD: Five corners describes a pentagon-like shape, not a rectangle.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-005',
    activityId: '5/26',
    sequence: 5,
    format: 'Fact',
    focus: 'Astronomy',
    title: 'The Moon reflects sunlight.',
    prompt: 'The Moon does not make its own visible light. It appears bright because sunlight reflects from its surface.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-006',
    activityId: '6/26',
    sequence: 6,
    format: 'Question',
    focus: 'Navigation',
    title: 'Which object is commonly used to tell direction?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Compass',
      'Teacup',
      'Stapler',
      'Paintbrush'
    ],
    correctIndex: 0,
    rationale: 'A: A compass is commonly used to identify direction.\nB: A teacup is used for drinking.\nC: A stapler is used to fasten papers.\nD: A paintbrush is used to apply paint.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-007',
    activityId: '7/26',
    sequence: 7,
    format: 'Fact',
    focus: 'Alphabetizing',
    title: 'Alphabetical order follows letter sequence.',
    prompt: 'Alphabetizing arranges words by comparing their letters from left to right.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-008',
    activityId: '8/26',
    sequence: 8,
    format: 'Question',
    focus: 'Alphabetizing',
    title: 'Which word would usually come first alphabetically?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Apple',
      'Banana',
      'Carrot',
      'Dog'
    ],
    correctIndex: 0,
    rationale: 'A: Apple begins with A.\nB: Banana begins with B, which follows A.\nC: Carrot begins with C, which follows A and B.\nD: Dog begins with D, which follows A, B, and C.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-009',
    activityId: '9/26',
    sequence: 9,
    format: 'Fact',
    focus: 'Recipes',
    title: 'Recipes usually list ingredients and steps.',
    prompt: 'A recipe commonly separates what is needed from what should be done, making the instructions easier to follow.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-010',
    activityId: '10/26',
    sequence: 10,
    format: 'Question',
    focus: 'Kitchen tools',
    title: 'Which tool is commonly used to measure liquid volume in a kitchen?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Hammer',
      'Measuring cup',
      'Envelope',
      'Comb'
    ],
    correctIndex: 1,
    rationale: 'A: A hammer is used for tasks such as driving nails.\nB: A measuring cup is commonly used to measure liquid volume.\nC: An envelope is used to hold papers or mail.\nD: A comb is used for hair.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-011',
    activityId: '11/26',
    sequence: 11,
    format: 'Fact',
    focus: 'Libraries',
    title: 'Libraries organize materials so they can be found again.',
    prompt: 'Books and other items are often grouped by topic, author, or catalog number to make searching easier.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-012',
    activityId: '12/26',
    sequence: 12,
    format: 'Question',
    focus: 'Reading',
    title: 'What is a bookmark used for?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Stirring soup',
      'Holding a door open',
      'Marking a page',
      'Sharpening a pencil'
    ],
    correctIndex: 2,
    rationale: 'A: A bookmark is not used to stir soup.\nB: A bookmark is not designed to hold a door open.\nC: A bookmark marks a place in a book or document.\nD: A bookmark is not used to sharpen pencils.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-013',
    activityId: '13/26',
    sequence: 13,
    format: 'Fact',
    focus: 'Plants',
    title: 'Many plants need light, water, and suitable conditions.',
    prompt: 'Plant growth depends on the type of plant and its environment, including light, water, temperature, and soil conditions.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-014',
    activityId: '14/26',
    sequence: 14,
    format: 'Question',
    focus: 'Plants',
    title: 'What may help a houseplant when its soil is dry?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Cover it with a book',
      'Turn off every light',
      'Remove all leaves',
      'Water it appropriately'
    ],
    correctIndex: 3,
    rationale: 'A: Covering it with a book does not address dry soil.\nB: Removing light does not add water to dry soil.\nC: Removing all leaves would usually harm the plant.\nD: Watering appropriately may help when soil is dry.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-015',
    activityId: '15/26',
    sequence: 15,
    format: 'Fact',
    focus: 'Maps',
    title: 'A map legend explains symbols.',
    prompt: 'A legend, sometimes called a key, helps readers understand what colors, lines, and icons mean on a map.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-016',
    activityId: '16/26',
    sequence: 16,
    format: 'Question',
    focus: 'Maps',
    title: 'What part of a map tells you what symbols mean?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Scale bar only',
      'Page number',
      'Legend or key',
      'Compass needle only'
    ],
    correctIndex: 2,
    rationale: 'A: A scale bar helps estimate distance, not symbol meaning.\nB: A page number identifies a page.\nC: A legend or key explains map symbols.\nD: A compass needle shows direction, not symbol meaning.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-017',
    activityId: '17/26',
    sequence: 17,
    format: 'Fact',
    focus: 'Music',
    title: 'Tempo describes musical speed.',
    prompt: 'Tempo refers to how fast or slow music is performed.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-018',
    activityId: '18/26',
    sequence: 18,
    format: 'Question',
    focus: 'Music',
    title: 'Which item is a musical instrument?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Violin',
      'Backpack',
      'Curtain',
      'Flashlight'
    ],
    correctIndex: 0,
    rationale: 'A: A violin is a musical instrument.\nB: A backpack is used to carry items.\nC: A curtain covers a window or opening.\nD: A flashlight provides portable light.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-019',
    activityId: '19/26',
    sequence: 19,
    format: 'Fact',
    focus: 'Recycling',
    title: 'Recycling labels help sort materials.',
    prompt: 'Labels and local rules can help people decide whether an item belongs in trash, recycling, or another collection stream.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-020',
    activityId: '20/26',
    sequence: 20,
    format: 'Question',
    focus: 'Everyday materials',
    title: 'Which item is commonly made of paper?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Screwdriver',
      'Notebook',
      'Glass jar',
      'Metal spoon'
    ],
    correctIndex: 1,
    rationale: 'A: A screwdriver is usually made with metal and a handle material.\nB: A notebook is commonly made with paper pages.\nC: A glass jar is made of glass.\nD: A metal spoon is made of metal.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-021',
    activityId: '21/26',
    sequence: 21,
    format: 'Fact',
    focus: 'Digital habits',
    title: 'Unique passwords are harder to guess.',
    prompt: 'Using a different password for each account can reduce the chance that one exposed password affects many accounts.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-022',
    activityId: '22/26',
    sequence: 22,
    format: 'Question',
    focus: 'Digital habits',
    title: 'Which password habit is generally safer?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Use the same short password everywhere',
      'Share passwords by text message',
      'Use unique passwords for different accounts',
      'Write passwords on public signs'
    ],
    correctIndex: 2,
    rationale: 'A: Reusing one short password can increase risk.\nB: Sharing passwords by text message can expose them.\nC: Unique passwords reduce repeated use across accounts.\nD: Posting passwords publicly is unsafe.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-023',
    activityId: '23/26',
    sequence: 23,
    format: 'Fact',
    focus: 'Weather',
    title: 'Weather forecasts estimate future conditions.',
    prompt: 'Forecasts use observations and models to estimate conditions such as temperature, rain, wind, and cloud cover.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-024',
    activityId: '24/26',
    sequence: 24,
    format: 'Question',
    focus: 'Weather',
    title: 'Which tool is commonly used to check temperature?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Ruler',
      'Whisk',
      'Notebook',
      'Thermometer'
    ],
    correctIndex: 3,
    rationale: 'A: A ruler measures length.\nB: A whisk is used for mixing.\nC: A notebook is used for writing.\nD: A thermometer is commonly used to check temperature.',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-025',
    activityId: '25/26',
    sequence: 25,
    format: 'Fact',
    focus: 'Documents',
    title: 'A table of contents points readers to sections.',
    prompt: 'A table of contents lists headings or chapters with page numbers so readers can find material more quickly.',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
    ],
    correctIndex: 0,
    rationale: '',
    citationNumbers: '',
    citationReferences: ''
  },
  {
    id: 'control-content-026',
    activityId: '26/26',
    sequence: 26,
    format: 'Question',
    focus: 'Documents',
    title: 'Where would you look to find where a chapter begins?',
    prompt: '',
    mediaType: '',
    mediaPath: '',
    mediaAlt: '',
    image: '',
    choices: [
      'Table of contents',
      'Shoe size tag',
      'Kitchen timer',
      'Window latch'
    ],
    correctIndex: 0,
    rationale: 'A: A table of contents lists where chapters or sections begin.\nB: A shoe size tag gives footwear size information.\nC: A kitchen timer tracks time.\nD: A window latch helps secure a window.',
    citationNumbers: '',
    citationReferences: ''
  }
];
